obj-$(CONFIG_MACH_VILLEC2) += board-villec2.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-gpiomux.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-keypad.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-mmc.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-storage.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-wifi.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-regulator.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-pmic.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-audio.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-camera.o
endif
obj-$(CONFIG_MACH_VILLEC2) += display/

