
#ifndef _LINUX_SNMP_H
#define _LINUX_SNMP_H

enum
{
	IPSTATS_MIB_NUM = 0,
	IPSTATS_MIB_INPKTS,			
	IPSTATS_MIB_INHDRERRORS,		
	IPSTATS_MIB_INTOOBIGERRORS,		
	IPSTATS_MIB_INNOROUTES,			
	IPSTATS_MIB_INADDRERRORS,		
	IPSTATS_MIB_INUNKNOWNPROTOS,		
	IPSTATS_MIB_INTRUNCATEDPKTS,		
	IPSTATS_MIB_INDISCARDS,			
	IPSTATS_MIB_INDELIVERS,			
	IPSTATS_MIB_OUTFORWDATAGRAMS,		
	IPSTATS_MIB_OUTPKTS,			
	IPSTATS_MIB_OUTDISCARDS,		
	IPSTATS_MIB_OUTNOROUTES,		
	IPSTATS_MIB_REASMTIMEOUT,		
	IPSTATS_MIB_REASMREQDS,			
	IPSTATS_MIB_REASMOKS,			
	IPSTATS_MIB_REASMFAILS,			
	IPSTATS_MIB_FRAGOKS,			
	IPSTATS_MIB_FRAGFAILS,			
	IPSTATS_MIB_FRAGCREATES,		
	IPSTATS_MIB_INMCASTPKTS,		
	IPSTATS_MIB_OUTMCASTPKTS,		
	IPSTATS_MIB_INBCASTPKTS,		
	IPSTATS_MIB_OUTBCASTPKTS,		
	IPSTATS_MIB_INOCTETS,			
	IPSTATS_MIB_OUTOCTETS,			
	IPSTATS_MIB_INMCASTOCTETS,		
	IPSTATS_MIB_OUTMCASTOCTETS,		
	IPSTATS_MIB_INBCASTOCTETS,		
	IPSTATS_MIB_OUTBCASTOCTETS,		
	__IPSTATS_MIB_MAX
};

enum
{
	ICMP_MIB_NUM = 0,
	ICMP_MIB_INMSGS,			
	ICMP_MIB_INERRORS,			
	ICMP_MIB_INDESTUNREACHS,		
	ICMP_MIB_INTIMEEXCDS,			
	ICMP_MIB_INPARMPROBS,			
	ICMP_MIB_INSRCQUENCHS,			
	ICMP_MIB_INREDIRECTS,			
	ICMP_MIB_INECHOS,			
	ICMP_MIB_INECHOREPS,			
	ICMP_MIB_INTIMESTAMPS,			
	ICMP_MIB_INTIMESTAMPREPS,		
	ICMP_MIB_INADDRMASKS,			
	ICMP_MIB_INADDRMASKREPS,		
	ICMP_MIB_OUTMSGS,			
	ICMP_MIB_OUTERRORS,			
	ICMP_MIB_OUTDESTUNREACHS,		
	ICMP_MIB_OUTTIMEEXCDS,			
	ICMP_MIB_OUTPARMPROBS,			
	ICMP_MIB_OUTSRCQUENCHS,			
	ICMP_MIB_OUTREDIRECTS,			
	ICMP_MIB_OUTECHOS,			
	ICMP_MIB_OUTECHOREPS,			
	ICMP_MIB_OUTTIMESTAMPS,			
	ICMP_MIB_OUTTIMESTAMPREPS,		
	ICMP_MIB_OUTADDRMASKS,			
	ICMP_MIB_OUTADDRMASKREPS,		
	__ICMP_MIB_MAX
};

#define __ICMPMSG_MIB_MAX 512	

enum
{
	ICMP6_MIB_NUM = 0,
	ICMP6_MIB_INMSGS,			
	ICMP6_MIB_INERRORS,			
	ICMP6_MIB_OUTMSGS,			
	ICMP6_MIB_OUTERRORS,			
	__ICMP6_MIB_MAX
};

#define __ICMP6MSG_MIB_MAX 512 

enum
{
	TCP_MIB_NUM = 0,
	TCP_MIB_RTOALGORITHM,			
	TCP_MIB_RTOMIN,				
	TCP_MIB_RTOMAX,				
	TCP_MIB_MAXCONN,			
	TCP_MIB_ACTIVEOPENS,			
	TCP_MIB_PASSIVEOPENS,			
	TCP_MIB_ATTEMPTFAILS,			
	TCP_MIB_ESTABRESETS,			
	TCP_MIB_CURRESTAB,			
	TCP_MIB_INSEGS,				
	TCP_MIB_OUTSEGS,			
	TCP_MIB_RETRANSSEGS,			
	TCP_MIB_INERRS,				
	TCP_MIB_OUTRSTS,			
	__TCP_MIB_MAX
};

enum
{
	UDP_MIB_NUM = 0,
	UDP_MIB_INDATAGRAMS,			
	UDP_MIB_NOPORTS,			
	UDP_MIB_INERRORS,			
	UDP_MIB_OUTDATAGRAMS,			
	UDP_MIB_RCVBUFERRORS,			
	UDP_MIB_SNDBUFERRORS,			
	__UDP_MIB_MAX
};

enum
{
	LINUX_MIB_NUM = 0,
	LINUX_MIB_SYNCOOKIESSENT,		/* SyncookiesSent */
	LINUX_MIB_SYNCOOKIESRECV,		/* SyncookiesRecv */
	LINUX_MIB_SYNCOOKIESFAILED,		/* SyncookiesFailed */
	LINUX_MIB_EMBRYONICRSTS,		/* EmbryonicRsts */
	LINUX_MIB_PRUNECALLED,			/* PruneCalled */
	LINUX_MIB_RCVPRUNED,			/* RcvPruned */
	LINUX_MIB_OFOPRUNED,			/* OfoPruned */
	LINUX_MIB_OUTOFWINDOWICMPS,		/* OutOfWindowIcmps */
	LINUX_MIB_LOCKDROPPEDICMPS,		/* LockDroppedIcmps */
	LINUX_MIB_ARPFILTER,			/* ArpFilter */
	LINUX_MIB_TIMEWAITED,			/* TimeWaited */
	LINUX_MIB_TIMEWAITRECYCLED,		/* TimeWaitRecycled */
	LINUX_MIB_TIMEWAITKILLED,		/* TimeWaitKilled */
	LINUX_MIB_PAWSPASSIVEREJECTED,		/* PAWSPassiveRejected */
	LINUX_MIB_PAWSACTIVEREJECTED,		/* PAWSActiveRejected */
	LINUX_MIB_PAWSESTABREJECTED,		/* PAWSEstabRejected */
	LINUX_MIB_DELAYEDACKS,			/* DelayedACKs */
	LINUX_MIB_DELAYEDACKLOCKED,		/* DelayedACKLocked */
	LINUX_MIB_DELAYEDACKLOST,		/* DelayedACKLost */
	LINUX_MIB_LISTENOVERFLOWS,		/* ListenOverflows */
	LINUX_MIB_LISTENDROPS,			/* ListenDrops */
	LINUX_MIB_TCPPREQUEUED,			/* TCPPrequeued */
	LINUX_MIB_TCPDIRECTCOPYFROMBACKLOG,	/* TCPDirectCopyFromBacklog */
	LINUX_MIB_TCPDIRECTCOPYFROMPREQUEUE,	/* TCPDirectCopyFromPrequeue */
	LINUX_MIB_TCPPREQUEUEDROPPED,		/* TCPPrequeueDropped */
	LINUX_MIB_TCPHPHITS,			/* TCPHPHits */
	LINUX_MIB_TCPHPHITSTOUSER,		/* TCPHPHitsToUser */
	LINUX_MIB_TCPPUREACKS,			/* TCPPureAcks */
	LINUX_MIB_TCPHPACKS,			/* TCPHPAcks */
	LINUX_MIB_TCPRENORECOVERY,		/* TCPRenoRecovery */
	LINUX_MIB_TCPSACKRECOVERY,		/* TCPSackRecovery */
	LINUX_MIB_TCPSACKRENEGING,		/* TCPSACKReneging */
	LINUX_MIB_TCPFACKREORDER,		/* TCPFACKReorder */
	LINUX_MIB_TCPSACKREORDER,		/* TCPSACKReorder */
	LINUX_MIB_TCPRENOREORDER,		/* TCPRenoReorder */
	LINUX_MIB_TCPTSREORDER,			/* TCPTSReorder */
	LINUX_MIB_TCPFULLUNDO,			/* TCPFullUndo */
	LINUX_MIB_TCPPARTIALUNDO,		/* TCPPartialUndo */
	LINUX_MIB_TCPDSACKUNDO,			/* TCPDSACKUndo */
	LINUX_MIB_TCPLOSSUNDO,			/* TCPLossUndo */
	LINUX_MIB_TCPLOSTRETRANSMIT,		/* TCPLostRetransmit */
	LINUX_MIB_TCPRENOFAILURES,		/* TCPRenoFailures */
	LINUX_MIB_TCPSACKFAILURES,		/* TCPSackFailures */
	LINUX_MIB_TCPLOSSFAILURES,		/* TCPLossFailures */
	LINUX_MIB_TCPFASTRETRANS,		/* TCPFastRetrans */
	LINUX_MIB_TCPFORWARDRETRANS,		/* TCPForwardRetrans */
	LINUX_MIB_TCPSLOWSTARTRETRANS,		/* TCPSlowStartRetrans */
	LINUX_MIB_TCPTIMEOUTS,			/* TCPTimeouts */
	LINUX_MIB_TCPRENORECOVERYFAIL,		/* TCPRenoRecoveryFail */
	LINUX_MIB_TCPSACKRECOVERYFAIL,		/* TCPSackRecoveryFail */
	LINUX_MIB_TCPSCHEDULERFAILED,		/* TCPSchedulerFailed */
	LINUX_MIB_TCPRCVCOLLAPSED,		/* TCPRcvCollapsed */
	LINUX_MIB_TCPDSACKOLDSENT,		/* TCPDSACKOldSent */
	LINUX_MIB_TCPDSACKOFOSENT,		/* TCPDSACKOfoSent */
	LINUX_MIB_TCPDSACKRECV,			/* TCPDSACKRecv */
	LINUX_MIB_TCPDSACKOFORECV,		/* TCPDSACKOfoRecv */
	LINUX_MIB_TCPABORTONDATA,		/* TCPAbortOnData */
	LINUX_MIB_TCPABORTONCLOSE,		/* TCPAbortOnClose */
	LINUX_MIB_TCPABORTONMEMORY,		/* TCPAbortOnMemory */
	LINUX_MIB_TCPABORTONTIMEOUT,		/* TCPAbortOnTimeout */
	LINUX_MIB_TCPABORTONLINGER,		/* TCPAbortOnLinger */
	LINUX_MIB_TCPABORTFAILED,		/* TCPAbortFailed */
	LINUX_MIB_TCPMEMORYPRESSURES,		/* TCPMemoryPressures */
	LINUX_MIB_TCPSACKDISCARD,		/* TCPSACKDiscard */
	LINUX_MIB_TCPDSACKIGNOREDOLD,		/* TCPSACKIgnoredOld */
	LINUX_MIB_TCPDSACKIGNOREDNOUNDO,	/* TCPSACKIgnoredNoUndo */
	LINUX_MIB_TCPSPURIOUSRTOS,		/* TCPSpuriousRTOs */
	LINUX_MIB_TCPMD5NOTFOUND,		/* TCPMD5NotFound */
	LINUX_MIB_TCPMD5UNEXPECTED,		/* TCPMD5Unexpected */
	LINUX_MIB_SACKSHIFTED,
	LINUX_MIB_SACKMERGED,
	LINUX_MIB_SACKSHIFTFALLBACK,
	LINUX_MIB_TCPBACKLOGDROP,
	LINUX_MIB_TCPMINTTLDROP, 
	LINUX_MIB_TCPDEFERACCEPTDROP,
	LINUX_MIB_IPRPFILTER, /* IP Reverse Path Filter (rp_filter) */
	LINUX_MIB_TCPTIMEWAITOVERFLOW,		/* TCPTimeWaitOverflow */
	LINUX_MIB_TCPREQQFULLDOCOOKIES,		/* TCPReqQFullDoCookies */
	LINUX_MIB_TCPREQQFULLDROP,		/* TCPReqQFullDrop */
	LINUX_MIB_TCPRETRANSFAIL,		/* TCPRetransFail */
	LINUX_MIB_TCPRCVCOALESCE,			/* TCPRcvCoalesce */
	LINUX_MIB_TCPCHALLENGEACK,		/* TCPChallengeACK */
	LINUX_MIB_TCPSYNCHALLENGE,		/* TCPSYNChallenge */
	__LINUX_MIB_MAX
};

enum
{
	LINUX_MIB_XFRMNUM = 0,
	LINUX_MIB_XFRMINERROR,			
	LINUX_MIB_XFRMINBUFFERERROR,		
	LINUX_MIB_XFRMINHDRERROR,		
	LINUX_MIB_XFRMINNOSTATES,		
	LINUX_MIB_XFRMINSTATEPROTOERROR,	
	LINUX_MIB_XFRMINSTATEMODEERROR,		
	LINUX_MIB_XFRMINSTATESEQERROR,		
	LINUX_MIB_XFRMINSTATEEXPIRED,		
	LINUX_MIB_XFRMINSTATEMISMATCH,		
	LINUX_MIB_XFRMINSTATEINVALID,		
	LINUX_MIB_XFRMINTMPLMISMATCH,		
	LINUX_MIB_XFRMINNOPOLS,			
	LINUX_MIB_XFRMINPOLBLOCK,		
	LINUX_MIB_XFRMINPOLERROR,		
	LINUX_MIB_XFRMOUTERROR,			
	LINUX_MIB_XFRMOUTBUNDLEGENERROR,	
	LINUX_MIB_XFRMOUTBUNDLECHECKERROR,	
	LINUX_MIB_XFRMOUTNOSTATES,		
	LINUX_MIB_XFRMOUTSTATEPROTOERROR,	
	LINUX_MIB_XFRMOUTSTATEMODEERROR,	
	LINUX_MIB_XFRMOUTSTATESEQERROR,		
	LINUX_MIB_XFRMOUTSTATEEXPIRED,		
	LINUX_MIB_XFRMOUTPOLBLOCK,		
	LINUX_MIB_XFRMOUTPOLDEAD,		
	LINUX_MIB_XFRMOUTPOLERROR,		
	LINUX_MIB_XFRMFWDHDRERROR,		
	__LINUX_MIB_XFRMMAX
};

#endif	
