# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/villec2/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/htc/villec2/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/htc/villec2/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/htc/villec2/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/htc/villec2/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
  vendor/htc/villec2/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/htc/villec2/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
  vendor/htc/villec2/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/htc/villec2/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/htc/villec2/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/villec2/proprietary/bin/cand:system/bin/cand \
  vendor/htc/villec2/proprietary/bin/charging:system/bin/charging \
  vendor/htc/villec2/proprietary/bin/htcbatt:system/bin/htcbatt \
  vendor/htc/villec2/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/htc/villec2/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/htc/villec2/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/htc/villec2/proprietary/bin/netsharing:system/bin/netsharing \
  vendor/htc/villec2/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/htc/villec2/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/villec2/proprietary/bin/thermald:system/bin/thermald \
  vendor/htc/villec2/proprietary/bin/zchgd:system/bin/zchgd \
  vendor/htc/villec2/proprietary/bin/awb_camera:system/bin/awb_camera \
  vendor/htc/villec2/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/villec2/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/villec2/proprietary/lib/libcam_oem_plugin.so:system/lib/libcam_oem_plugin.so \
  vendor/htc/villec2/proprietary/lib/libDxOAF.so:system/lib/libDxOAF.so \
  vendor/htc/villec2/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/villec2/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/htc/villec2/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
  vendor/htc/villec2/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/htc/villec2/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/villec2/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/villec2/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
  vendor/htc/villec2/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
  vendor/htc/villec2/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/villec2/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
  vendor/htc/villec2/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/villec2/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:system/lib/libchromatix_s5k3h2yx_default_video.so \
  vendor/htc/villec2/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:system/lib/libchromatix_s5k3h2yx_hdr.so \
  vendor/htc/villec2/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:system/lib/libchromatix_s5k3h2yx_hfr.so \
  vendor/htc/villec2/proprietary/lib/libchromatix_s5k3h2yx_preview.so:system/lib/libchromatix_s5k3h2yx_preview.so \
  vendor/htc/villec2/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:system/lib/libchromatix_s5k3h2yx_zsl.so \
  vendor/htc/villec2/proprietary/etc/agps_rm:system/etc/agps_rm \
  vendor/htc/villec2/proprietary/etc/calibration:system/etc/calibration \
  vendor/htc/villec2/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
  vendor/htc/villec2/proprietary/etc/firmware/BCM4330B1_002.001.003.0833.0845.hcd:system/etc/firmware/BCM4330B1_002.001.003.0833.0845.hcd \
  vendor/htc/villec2/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
  vendor/htc/villec2/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
  vendor/htc/villec2/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
  vendor/htc/villec2/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/htc/villec2/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/htc/villec2/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
  vendor/htc/villec2/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
  vendor/htc/villec2/proprietary/etc/firmware/fw_bcm4330_p2p_b2.bin:system/etc/firmware/fw_bcm4330_p2p_b2.bin \
  vendor/htc/villec2/proprietary/etc/firmware/fw_bcm4330_apsta_b2.bin:system/etc/firmware/fw_bcm4330_apsta_b2.bin \
  vendor/htc/villec2/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
  vendor/htc/villec2/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
  vendor/htc/villec2/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
  vendor/htc/villec2/proprietary/etc/firmware/fw_bcm4330_b2.bin:system/etc/firmware/fw_bcm4330_b2.bin \
  vendor/htc/villec2/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
  vendor/htc/villec2/proprietary/etc/firmware/default_bak.acdb:system/etc/firmware/default_bak.acdb \
  vendor/htc/villec2/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
  vendor/htc/villec2/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
  vendor/htc/villec2/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/villec2/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/villec2/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/villec2/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/villec2/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/villec2/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/villec2/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/htc/villec2/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/villec2/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/villec2/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/villec2/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
  vendor/htc/villec2/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/villec2/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/villec2/proprietary/lib/libdll.so:system/lib/libdll.so \
  vendor/htc/villec2/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/htc/villec2/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/villec2/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
  vendor/htc/villec2/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/villec2/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/htc/villec2/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/villec2/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/htc/villec2/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/villec2/proprietary/lib/hw/sensors.villec2.so:system/lib/hw/sensors.villec2.so \
  vendor/htc/villec2/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/htc/villec2/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
  vendor/htc/villec2/proprietary/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
  vendor/htc/villec2/proprietary/lib/libmpl.so:system/lib/libmpl.so \
  vendor/htc/villec2/proprietary/lib/libv8.so:system/lib/libv8.so  \
  vendor/htc/villec2/legacy/hw/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
  vendor/htc/villec2/legacy/hw/copybit.msm8660.so:system/lib/hw/copybit.msm8660.so \
  vendor/htc/villec2/legacy/hw/gralloc.msm8660.so:system/lib/hw/gralloc.msm8660.so \
  vendor/htc/villec2/legacy/hw/hwcomposer.msm8660.so:system/lib/hw/hwcomposer.msm8660.so \
  vendor/htc/villec2/legacy/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so              \
  vendor/htc/villec2/legacy/libgenlock.so:system/lib/libgenlock.so              \
  vendor/htc/villec2/legacy/libhwcexternal.so:system/lib/libhwcexternal.so               \
  vendor/htc/villec2/legacy/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so               \
  vendor/htc/villec2/legacy/libhwcservice.so:system/lib/libhwcservice.so                 \
  vendor/htc/villec2/legacy/libmemalloc.so:system/lib/libmemalloc.so            \
  vendor/htc/villec2/legacy/libmm-omxcore.so:system/lib/libmm-omxcore.so             \
  vendor/htc/villec2/legacy/libOmxCore.so:system/lib/libOmxCore.so                \
  vendor/htc/villec2/legacy/libOmxVdec.so:system/lib/libOmxVdec.so              \
  vendor/htc/villec2/legacy/libOmxVenc.so:system/lib/libOmxVenc.so                \
  vendor/htc/villec2/legacy/liboverlay.so:system/lib/liboverlay.so               \
  vendor/htc/villec2/legacy/libqdutils.so:system/lib/libqdutils.so                  \
  vendor/htc/villec2/legacy/libselinux.so:system/lib/libselinux.so                  \
  vendor/htc/villec2/legacy/libstagefrighthw.so:system/lib/libstagefrighthw.so      \
  vendor/htc/villec2/include/OMX_Audio.h:obj/include/mm-core/omxcore/OMX_Audio.h      \
  vendor/htc/villec2/include/OMX_Component.h:obj/include/mm-core/omxcore/OMX_Component.h      \
  vendor/htc/villec2/include/OMX_ContentPipe.h:obj/include/mm-core/omxcore/OMX_ContentPipe.h      \
  vendor/htc/villec2/include/OMX_Core.h:obj/include/mm-core/omxcore/OMX_Core.h     \
  vendor/htc/villec2/include/OMX_Image.h:obj/include/mm-core/omxcore/OMX_Image.h      \
  vendor/htc/villec2/include/OMX_Index.h:obj/include/mm-core/omxcore/OMX_Index.h      \
  vendor/htc/villec2/include/OMX_IVCommon.h:obj/include/mm-core/omxcore/OMX_IVCommon.h      \
  vendor/htc/villec2/include/OMX_Other.h:obj/include/mm-core/omxcore/OMX_Other.h      \
  vendor/htc/villec2/include/OMX_QCOMExtns.h:obj/include/mm-core/omxcore/OMX_QCOMExtns.h      \
  vendor/htc/villec2/include/OMX_Types.h:obj/include/mm-core/omxcore/OMX_Types.h      \
  vendor/htc/villec2/include/OMX_Video.h:obj/include/mm-core/omxcore/OMX_Video.h     \
  vendor/htc/villec2/include/qc_omx_common.h:obj/include/mm-core/omxcore/qc_omx_common.h     \
  vendor/htc/villec2/include/qc_omx_component.h:obj/include/mm-core/omxcore/qc_omx_component.h      \
  vendor/htc/villec2/include/qc_omx_msg.h:obj/include/mm-core/omxcore/qc_omx_msg.h      \
  vendor/htc/villec2/include/QOMX_AudioExtensions.h:obj/include/mm-core/omxcore/QOMX_AudioExtensions.h      \
  vendor/htc/villec2/include/QOMX_AudioIndexExtensions.h:obj/include/mm-core/omxcore/QOMX_AudioIndexExtensions.h     \
  vendor/htc/villec2/include/OMX_CoreExt.h:obj/include/mm-core/omxcore/OMX_CoreExt.h     \
  vendor/htc/villec2/include/QOMX_CoreExtensions.h:obj/include/mm-core/omxcore/QOMX_CoreExtensions.h      \
  vendor/htc/villec2/include/QOMX_FileFormatExtensions.h:obj/include/mm-core/omxcore/QOMX_FileFormatExtensions.h     \
  vendor/htc/villec2/include/QOMX_IVCommonExtensions.h:obj/include/mm-core/omxcore/QOMX_IVCommonExtensions.h      \
  vendor/htc/villec2/include/QOMX_SourceExtensions.h:obj/include/mm-core/omxcore/QOMX_SourceExtensions.h     \
  vendor/htc/villec2/include/QOMX_VideoExtensions.h:obj/include/mm-core/omxcore/QOMX_VideoExtensions.h      \
  vendor/htc/villec2/include/OMX_IndexExt.h:obj/include/mm-core/omxcore/OMX_IndexExt.h     \
  vendor/htc/villec2/include/QOMX_StreamingExtensions.h:obj/include/mm-core/omxcore/QOMX_StreamingExtensions.h     \
  vendor/htc/villec2/include/QCMediaDefs.h:obj/include/mm-core/omxcore/QCMediaDefs.h      \
  vendor/htc/villec2/include/QCMetaData.h:obj/include/mm-core/omxcore/QCMetaData.h      \

